#!/bin/sh
# Usage:
# ./run # Runs the full web app
# ./run test # Runs the testing suite

set -eu

SCRIPT_DIR="$(CDPATH= command cd -- "$(dirname -- "$0")" && pwd -P)"

export APP_ROOT="$SCRIPT_DIR/app"
export STATIC_FOLDER="$APP_ROOT/static"

# Clear out build directory
rm -f "$SCRIPT_DIR"/app/static/build/*.js
rm -f "$SCRIPT_DIR"/app/static/build/*.css


python3 -um app \
  --host "${ADDRESS:-0.0.0.0}" \
  --port "${PORT:-"${EXPOSE_PORT:-5000}}"

